"""
DARKWIN — Reporting | Markdown Report Generator
Formats collected scan results into a structured Markdown document.
"""

import json
from pathlib import Path
from datetime import datetime
from core.logger import get_logger


def generate(results: dict, output_path: str) -> str:
    """
    Format scan results as a Markdown report and write to output directory.

    Args:
        results:     Dictionary from report_builder.collect_results().
        output_path: Directory to write the report.md file into.

    Returns:
        Path to the generated Markdown file.
    """
    log = get_logger(tool_name="markdown_report", target=results.get("target", "unknown"))

    Path(output_path).mkdir(parents=True, exist_ok=True)

    target = results.get("target", "Unknown Target")
    scan_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    modules = results.get("modules", {})

    lines = [
        f"# DARKWIN Scan Report",
        f"",
        f"| Field | Value |",
        f"|-------|-------|",
        f"| **Target** | `{target}` |",
        f"| **Scan Date** | {scan_date} |",
        f"| **Output Dir** | `{results.get('output_dir', 'N/A')}` |",
        f"| **Total Modules** | {len(modules)} |",
        f"| **Generated By** | DARKWIN v1.0.0 |",
        f"",
        f"---",
        f"",
    ]

    for module_key, data in sorted(modules.items()):
        file_path = data.get("file", "")
        file_type = data.get("type", "txt")
        content = data.get("content", "")

        lines.append(f"## {module_key.replace('_', ' ').title()}")
        lines.append(f"")
        lines.append(f"**Source file:** `{file_path}`")
        lines.append(f"")

        if file_type == "json" and isinstance(content, dict):
            lines.append("```json")
            lines.append(json.dumps(content, indent=2)[:3000])  # Limit length
            lines.append("```")
        else:
            content_str = str(content)[:3000]  # Limit length
            if content_str.strip():
                lines.append("```")
                lines.append(content_str)
                lines.append("```")
            else:
                lines.append("*No output captured.*")

        lines.append("")
        lines.append("---")
        lines.append("")

    out_file = Path(output_path) / "report.md"
    out_file.write_text("\n".join(lines), encoding="utf-8")
    log.success(f"Markdown report generated → {out_file}")
    return str(out_file)
